FROM ubuntu:latest
ARG ARG_ENV
ENV APP_ENV=$ARG_ENV
RUN apt-get update && apt-get install -y \
    apache2
COPY app/index.html /var/www/html/index.html
RUN a2enmod rewrite
RUN a2enmod ssl
ADD start.sh /
RUN chmod +x /start.sh
EXPOSE 80
ENTRYPOINT [ "/bin/bash", "/start.sh" ]