apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-main
  namespace: argocd-main
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: argocd-main
  template:
    metadata:
      labels:
        app: argocd-main
    spec:
      containers:
        - name: argocd-main
          image: 611434859417.dkr.ecr.us-east-1.amazonaws.com/agrocd:main-b9c3f06
          imagePullPolicy:
          ports:
            - containerPort: 80
