name: argocd-eks ## $Project Name / $Branch

on:
  push:
    branches:
      - main ## CHANGE Branch Name HERE !!!

permissions:
  id-token: write  ## NEEDED!!!
  contents: write  ## CHANGED to 'write' so the runner can push manifest updates back to GitHub

jobs:
  credentials_build_deploy:
    name: Building and Pushing the Image
    runs-on: [ubuntu-latest] ## private/public runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::611434859417:role/GitHubActionRole-EKS  # change AWS account HERE
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2      

    - name: Build, tag, push image, and update manifest
      env:
        ECR_REGISTRY:  ${{ steps.login-ecr.outputs.registry }}         
        ECR_REPOSITORY: agrocd  ## CHANGE ECR Name HERE!!!
      run: |
        IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")
        ENV=main                                    ## CHANGE Env Name HERE!!!
        BRANCH=${GITHUB_REF##*/}
        FULL_IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH-$IMAGE_TAG"
        
        # 1. Build and push the image to ECR
        docker build -f Dockerfile-$ENV --build-arg ARG_ENV=${ENV} -t $FULL_IMAGE_URI .
        docker push $FULL_IMAGE_URI
        
        # 2. Dynamically update the image key in deployment.yaml using yq
        cd manifest/main                            ## CHANGE DIR Name HERE!!!
        yq -i '.spec.template.spec.containers[0].image = env(FULL_IMAGE_URI)' deployment.yaml

    - name: Commit and Push Manifest Changes to GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Stage the updated manifest file
        git add manifest/main/deployment.yaml       ## CHANGE DIR Name HERE!!!
        
        # [skip ci] prevents this commit from triggering another workflow run infinitely
        git commit -m "image deployment update: auto-updated by github actions [skip ci]"
        
        # Push the changes back to your tracking branch
        git push origin main